### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kankaristo** [jakesankey/line-diff-details#18] opened 2016-04-04 09:37 UTC
Atom points to https://github.com/jakesankey/line-diff-details/issues/7, but this is probably a different issue with a similar error message.

I got this error after doing a commit from the command line, going back to Atom, and clicking on a diff marker in the gutter, which shouldn't have been there anymore.

Making some minor edit in the file hides the stale diff markers and everything is back to normal. So, the real bug is probably in `git-diff`, but an if-guard in `line-diff-details` probably wouldn't hurt.

**Atom Version**: 1.7.0-beta2
**System**: Ubuntu 15.10
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.2.0

```
At /home/sami/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:44

TypeError: Cannot read property 'length' of undefined
    at LineDiffWorker.decorateDiffMarkers (/home/sami/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:44:67)
    at HTMLDivElement.<anonymous> (/home/sami/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:34:14)
    at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom-beta/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/usr/share/atom-beta/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by aljinovic** [comment] 2016-04-07 16:21
fixed in PR https://github.com/jakesankey/line-diff-details/pull/19

**Comment by lzrski** [comment] 2016-05-18 13:24
I had this error thrown when I clicked on gutter where line was removed.

**Comment by jakesankey** [comment] 2016-05-19 03:41
I'm sorry, I am unable to reproduce this error. When I follow the same steps you mentioned, upon returning to atom, the gutter markers disappear.

Perhaps #7 did indeed fix this. Please raise the issue again if you see it again.

**Closed by jakesankey** 2016-05-19 03:41 UTC

**Comment by danosier** [comment] 2016-08-11 22:54
I was able to reproduce this error. Removed second line of file, when clicking on line 1 to see changes, I get this error. 
Atom 1.9.5
line-diff-details 1.3.5
