### ISSUE TITLE
Deprecated selector in `line-diff-details\styles\line-diff-details.less`

### ISSUE THREAD

**Issue by 1ukaz** [jakesankey/line-diff-details#37] opened 2017-03-07 19:45 UTC
In `line-diff-details\styles\line-diff-details.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .line-diff-added` => `atom-text-editor.editor .line-diff-added`

* `atom-text-editor::shadow .line-diff-modified` => `atom-text-editor.editor .line-diff-modified`

* `atom-text-editor::shadow .line-diff-removed` => `atom-text-editor.editor .line-diff-removed`

* `atom-text-editor::shadow .line-diff-marker` => `atom-text-editor.editor .line-diff-marker`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by colin-kiegel** [comment] 2017-03-11 08:15
duplicate of #28

**Comment by 1ukaz** [comment] 2017-03-12 14:27
Of course is a duplicate @colin-kiegel I am probably not​ the only one using this package with Atom, and since the application reports it ... Do your maths. Would be great if it can be fixed or else, good bye. Uninstall ...

**Comment by jakesankey** [comment] 2017-03-12 15:14
@1ukaz, If you follow the trail to the open PR, you will see that it currently has conflicts. Once resolved, I can merge. You should also note that I am not actively working in or on Atom right now and but given this is open source, if you have urgent fixes you would like made,  feel free to contribute to the project via Pull Requests.

**Comment by colin-kiegel** [comment] 2017-03-12 20:33
@1ukaz I am a bit surprised by your strong reaction. This being a duplicate was merely an observation and I stated it for cross referencing. That's it. I was not suggesting to close it. :-)

**Comment by 1ukaz** [comment] 2017-03-12 21:07
@colin-kiegel if It sounded strong, I give you my apologies. It wasn't my intention. Is just my English Wich is very poor. Sorry for that. Honestly

**Comment by jakesankey** [comment] 2017-03-31 18:11
This was resolved in the last update.

**Closed by jakesankey** 2017-03-31 18:11 UTC
